### ISSUE TITLE
Eventloop applications always use the same response

### ISSUE THREAD

**Issue by odahcam** [projek-xyz/slim-plates#13]
Need a way to set the response for each request made to the application, in apps like Swoole the response is set only the first time and not for each request. A middleware would be nice for updating the response object inside the library each request.

**Comment by feryardiant** [comment]
Hi @odahcam 

Basically we have `setResponse($response)` method and you can use something like this.

```php
/**
 * @param \Psr\Http\Message\ServerRequestInterface $request
 * @param \Psr\Http\Message\ResponseInterface $response
 */
public function myMethod($request, $response)
{
    // do something with the $request 

    return $this->slimPlatesObj->setResponse($response)->render('my-template', []);
}
```
OR

```php
/**
 * @param \Psr\Http\Message\ServerRequestInterface $request
 */
public function myMethod($request)
{
    // do something with the $request

    $response = $this->responseFactory->createResponse();

    return $this->slimPlatesObj->setResponse($response)->render('my-template', []);
}
```

**Comment by odahcam** [comment]
Yep, the only problem with this approach is that subsequent requests will replace the reponse object the template engine is holding. One nice thing for handling this scenario would be to have a factory method so we could get a new instance for each request.

**Comment by feryardiant** [comment]
I'd love to see a simple repo to reproduce the issue.

Thanks

**Comment by feryardiant** [comment]
Closing this for now. Feel free to comment once you have more info according to the issue.
