### ISSUE TITLE
Need a method to set response obj

### ISSUE THREAD

**Issue by feryardiant** [projek-xyz/slim-plates#3]
Need a method with `\Psr\Http\Message\ResponseInterface` as param. So we don't need to pass it from `render()` method.

**Comment by feryardiant** [comment]
What about pass it from constructor?

**Comment by creasi** [comment]
![1187032_636654109687746_1507722257_n](https://cloud.githubusercontent.com/assets/11495172/11802066/c973a394-a31e-11e5-9ce4-73c32202252e.jpg)

**Comment by feryardiant** [comment]
As per b1e9442e, Now we can pass `\Psr\Http\Message\ResponseInterface` instance to the `__construct` second parameter:

```php
$view = new Projek\Slim\Plates($settings, $responseObj);
```

or

```php
$view = new Projek\Slim\Plates($settings);
$view->setReponse($responseObj);
```

So, no need to pass it from `render()` method. Simply

```php
$this->view->render('template_name', $data_array);
```
