### ISSUE TITLE
Doc upgrade needed: first param $response on render method

### ISSUE THREAD

**Issue by fernanrusan** [projek-xyz/slim-plates#5]
Hello!! I'm using your slim-plates integration, it's great, but I cannot run your example because render method's first param doesn't psr7 response.

I try remove render methods' s first param and OK:

// Define named route
$app->get('/hello/{name}', function ($request, $response, $args) {
    return $this->view->render('profile', [
        'name' => $args['name']
    ]);
})->setName('profile');

Change your doc please.

Thanks for your integration!

**Comment by feryardiant** [comment]
Thank you @fernanrusan :smile: 

cheers
