### ISSUE TITLE
Add method to call Plates render without $response

### ISSUE THREAD

**Issue by chriscarpenter12** [projek-xyz/slim-plates#6]
Can you add the ability to call Plates `render` without `$this->response->write()`?

For example creating email templates and using Plates for template inheritance. And attach the rendered html to an email body instead of returning a view for a web response.

Something like this maybe? This would save from instantiating Plates again with the needed settings since we are already.
```
public function renderWithNoResonse($name, array $data = [])
{
  return $this->plates->render($name, $data);
}
```

**Comment by feryardiant** [comment]
Basically you can simply use [`getPlates()`](https://github.com/projek-xyz/slim-plates/blob/master/src/Plates.php#L48-L56) method like this.

```php
return $this->view->getPlates()->render('email_tpl', $data);
```

**Comment by feryardiant** [comment]
I close it for now.
